services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=brevlypass
      - POSTGRESQL_DATABASE=brevly
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ../web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - app

volumes:
  pgdata:
  redisdata:
